const mongoose=require("mongoose");
const productSchema=new mongoose.Schema({
    category:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    seller:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    stock:{
        type:Number,
        required:true
    },
    ratingsCount:{
        type:Number,
        required:true
    },
    img:{
        type:String,
        required:true
    },
    shipping:{
        type:Number,
        required:true
    },
    quantity:{
        type:Number,
        required:true
    },
    date:{
        type:Date,
        default:Date.now
    }
});

module.exports=productSchema;